name: Netherboard
version: 2.0.0
description: Scoreboard API for your Bukkit Plugins.
author: MinusKube
website: https://github.com/MinusKube/netherboard
main: fr.minuskube.netherboard.bukkit.NetherboardPlugin